/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: super7 (https://sketchfab.com/super7)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/predator-s-3921d70ad5dd45d1861a1cdd9c49a228
Title: Predator S
*/

import React, { useState } from 'react'
import { useGLTF } from '@react-three/drei'
import PredatorCloakMaterial from './PredatorMaterial/PredatorMaterial'

export function Predator(props) {
  const { nodes, materials } = useGLTF('/predator_s-transformed.glb')
  const [hover, sethover] = useState(false)

  return (
    <group
      onPointerEnter={() => {
        sethover(true)
      }}
      onPointerLeave={() => {
        sethover(false)
      }}
      {...props}
      dispose={null}>
      <group scale={0.22}>
        <mesh geometry={nodes.Object_6.geometry}>
          <PredatorCloakMaterial originalMaterial={materials.cabeza} gridWidth={40} gridHeight={40} hover={hover} />
        </mesh>
        <mesh geometry={nodes.Object_8.geometry}>
          <PredatorCloakMaterial originalMaterial={materials.cuerpo} gridWidth={60} gridHeight={65} hover={hover} />
        </mesh>
        <mesh geometry={nodes.Object_10.geometry}>
          <PredatorCloakMaterial originalMaterial={materials.casco} gridWidth={20} gridHeight={20} hover={hover} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/predator_s-transformed.glb')
