/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: super7 (https://sketchfab.com/super7)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/predator-s-3921d70ad5dd45d1861a1cdd9c49a228
Title: Predator S
*/

import React, { useEffect, useMemo, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three/webgpu'
import PredatorCloakMaterial from './PredatorMaterial/PredatorMaterial'
import { hoverSettings } from './hoverSettings'

const noRaycast = () => null
const HOVER_SOUND_URL = '/freesound_community-predator-40909.mp3'

export function Predator(props) {
  const { nodes, materials } = useGLTF('/predator_s-transformed.glb')
  const [cloakActive, setCloakActive] = useState(false)
  const hoverAudioRef = useRef(null)
  const hitMaterial = useMemo(() => {
    const material = new THREE.MeshBasicNodeMaterial()
    material.transparent = true
    material.opacity = 0
    material.depthWrite = false
    return material
  }, [])

  useEffect(() => {
    const audio = new Audio(HOVER_SOUND_URL)
    audio.volume = 0.6
    audio.preload = 'auto'
    hoverAudioRef.current = audio

    return () => {
      audio.pause()
      audio.src = ''
      hoverAudioRef.current = null
    }
  }, [])

  const syncCloak = () => {
    setCloakActive(hoverSettings.hovered || hoverSettings.holding)
  }

  useEffect(() => {
    const startHold = (event) => {
      if (event.button !== undefined && event.button !== 0) return
      if (event.target?.closest?.('button, a, .ui-chrome')) return
      hoverSettings.setHolding(true)
      syncCloak()
    }

    const clearHold = () => {
      hoverSettings.setHolding(false)
      syncCloak()
    }

    window.addEventListener('pointerdown', startHold)
    window.addEventListener('pointerup', clearHold)
    window.addEventListener('pointercancel', clearHold)
    return () => {
      window.removeEventListener('pointerdown', startHold)
      window.removeEventListener('pointerup', clearHold)
      window.removeEventListener('pointercancel', clearHold)
    }
  }, [])

  const playHoverSound = () => {
    const audio = hoverAudioRef.current
    if (!audio) return
    audio.currentTime = 0
    audio.play().catch(() => {})
  }

  const stopHoverSound = () => {
    const audio = hoverAudioRef.current
    if (!audio) return
    audio.pause()
    audio.currentTime = 0
  }

  return (
    <group {...props} dispose={null}>
      <group scale={0.22}>
        <mesh geometry={nodes.Object_6.geometry} raycast={noRaycast}>
          <PredatorCloakMaterial
            materialName="PredatorCloak-Head"
            originalMaterial={materials.cabeza}
            gridWidth={40}
            gridHeight={40}
            hover={cloakActive}
          />
        </mesh>
        <mesh geometry={nodes.Object_8.geometry} raycast={noRaycast}>
          <PredatorCloakMaterial
            materialName="PredatorCloak-Body"
            originalMaterial={materials.cuerpo}
            gridWidth={60}
            gridHeight={65}
            hover={cloakActive}
          />
        </mesh>
        <mesh geometry={nodes.Object_10.geometry} raycast={noRaycast}>
          <PredatorCloakMaterial
            materialName="PredatorCloak-Helmet"
            originalMaterial={materials.casco}
            gridWidth={20}
            gridHeight={20}
            hover={cloakActive}
          />
        </mesh>
      </group>

      <mesh
        position={[0, 1.2, 0]}
        scale={[0.4, 1.1, 0.4]}
        material={hitMaterial}
        onPointerOver={(event) => {
          event.stopPropagation()
          hoverSettings.setHovered(true)
          syncCloak()
          document.body.style.cursor = 'pointer'
          playHoverSound()
        }}
        onPointerOut={() => {
          hoverSettings.setHovered(false)
          syncCloak()
          document.body.style.cursor = 'grab'
          stopHoverSound()
        }}>
        <sphereGeometry args={[1, 16, 16]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/predator_s-transformed.glb')
